clear
v = 'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGTGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
original = [v(1) ' ' v(2:4) ' ' v(5:7) ' ' v(8:10) ' ' v(11:13) ' ' v(14:16) ' ' v(17:19) ' ' v(20:22) ' ' v(23:25) ' ' v(26:28) ' ' v(29:31) ' ' v(32:34) ' ' v(35:37) ' ' v(38:40) ' ' v(41:43) ' ' v(44:46) ' ' v(47:49) ' ' v(50:52) ' ' v(53:55) ' ' v(56:58) ' ' v(59:61) ' ' v(62:64) ' ' v(65:67) ' ' v(68:70) ' ' v(71)];
var = ['GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCCGAAAGTGGGTTGTTCTGATCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCAGACAGTGGGTTGTTCTGATCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGCCCCGACAGTGGGTTGTTCTGATCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTAAGACCCGACAGTGGGTTGTTCTGATCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCCGAAAGTGGGTTATTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCAGACAGTGGGTTATTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGCCCCGACAGTGGGTTATTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTAAGACCCGACAGTGGGTTATTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCCGAAAGTGGATTGTTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGACCAGACAGTGGATTGTTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTCAGCCCCGACAGTGGATTGTTCTGGTCCATG'
'GACCGCCGGGGCCCAGCGCCGAAAGACGACGCTTGCGGGTAAGACCCGACAGTGGATTGTTCTGGTCCATG'
'GACCGCCGGGGCCAAGTGCCGAAAGCCGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCGGGACCCAGTGCCGAAAGCCGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCAGGGCCCAGTGCCGAAAGCCGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCACCGGGGCCCAGTGCCGAAAGCCGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCGGGGCCAAGTGCCGACAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCGGGACCCAGTGCCGACAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCAGGGCCCAGTGCCGACAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCACCGGGGCCCAGTGCCGACAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCGGGGCCAAGTGCAGAAAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCGGGACCCAGTGCAGAAAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCGCCAGGGCCCAGTGCAGAAAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG'
'GACCACCGGGGCCCAGTGCAGAAAGACGACGCTTGCGGGTCAGACCCGACAGCGGGTTGTTCTGGTCCATG']
blank = 'G ACC GCC GGG GCC CAG CGC CGA AAG ACG ACG CTT GTG GGT CAG ACC CGA CAG CGG GTT GTT CTG GTC CAT G'
blank(blank =='G')=' ';
blank(blank =='A')=' ';
blank(blank =='T')=' ';
blank(blank =='C')=' ';

for x = 1:size(var,1)
    b = blank;
v = var(x,:);
    v = [v(1) ' ' v(2:4) ' ' v(5:7) ' ' v(8:10) ' ' v(11:13) ' ' v(14:16) ' ' v(17:19) ' ' v(20:22) ' ' v(23:25) ' ' v(26:28) ' ' v(29:31) ' ' v(32:34) ' ' v(35:37) ' ' v(38:40) ' ' v(41:43) ' ' v(44:46) ' ' v(47:49) ' ' v(50:52) ' ' v(53:55) ' ' v(56:58) ' ' v(59:61) ' ' v(62:64) ' ' v(65:67) ' ' v(68:70) ' ' v(71)];
        b(v~=original)=v(v~=original);
    fprintf('%s\n',b);
end

for x = 1:size(var,1)
    f0=[];
    b = blank;
v = var(x,:);
    v = [v(1) ' ' v(2:4) ' ' v(5:7) ' ' v(8:10) ' ' v(11:13) ' ' v(14:16) ' ' v(17:19) ' ' v(20:22) ' ' v(23:25) ' ' v(26:28) ' ' v(29:31) ' ' v(32:34) ' ' v(35:37) ' ' v(38:40) ' ' v(41:43) ' ' v(44:46) ' ' v(47:49) ' ' v(50:52) ' ' v(53:55) ' ' v(56:58) ' ' v(59:61) ' ' v(62:64) ' ' v(65:67) ' ' v(68:70) ' ' v(71)];
        b(v~=original)=v(v~=original);
        f = find(v~=original);
        for y = 1:numel(f)
            f0(y)=f(y)-sum(original(1:f(y))==' ');
        end
    for y=1:sum(v~=original)
        fprintf('(%s%s>%s)',original(f(y)),num2str(f0(y)),b(f(y)));
    end
    fprintf('\n');
end